title: "Anthony Lembert, Resilience and Commitment in both Military Service and Academic Pursuits."
author: "Anthony Lembert"
description: "Oregon State University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "https://anthonylembert.github.io/", title: "Home"}
  - {title: "Resume", file: "resume.md"}
  - {title: "Blog", file: "blog.md"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:anthony.lembert@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/anthonylembert"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
